// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgGEDVW13kdXdFbV1TPHwgaIkOvtykriM',
    appId: '1:934493147073:web:51ecd6bd8b72041e172940',
    messagingSenderId: '934493147073',
    projectId: 'brokkers-3cf67',
    authDomain: 'brokkers-3cf67.firebaseapp.com',
    storageBucket: 'brokkers-3cf67.firebasestorage.app',
    measurementId: 'G-CC8ETHXLGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7JbzXnkgoJHD509lLjU7D96eqUjyK07g',
    appId: '1:934493147073:android:0efede8c792fd324172940',
    messagingSenderId: '934493147073',
    projectId: 'brokkers-3cf67',
    storageBucket: 'brokkers-3cf67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsGfd5ZL0qkBfEzwMBgx653LCK395BUOI',
    appId: '1:934493147073:ios:0a88b1a5979a487f172940',
    messagingSenderId: '934493147073',
    projectId: 'brokkers-3cf67',
    storageBucket: 'brokkers-3cf67.firebasestorage.app',
    iosBundleId: 'com.example.brokkrs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsGfd5ZL0qkBfEzwMBgx653LCK395BUOI',
    appId: '1:934493147073:ios:0a88b1a5979a487f172940',
    messagingSenderId: '934493147073',
    projectId: 'brokkers-3cf67',
    storageBucket: 'brokkers-3cf67.firebasestorage.app',
    iosBundleId: 'com.example.brokkrs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgGEDVW13kdXdFbV1TPHwgaIkOvtykriM',
    appId: '1:934493147073:web:7792349f22f8afee172940',
    messagingSenderId: '934493147073',
    projectId: 'brokkers-3cf67',
    authDomain: 'brokkers-3cf67.firebaseapp.com',
    storageBucket: 'brokkers-3cf67.firebasestorage.app',
    measurementId: 'G-1QXKTFEF22',
  );
}
